# Lab 2: NumPy and Vectorization

#### Objective

Demonstrate array-based operations and vectorization using NumPy.

#### Tasks Covered

- Creating a 2D NumPy array
- Computing row means and column maxima
- Normalizing columns to the range 0–1
- Applying broadcasting
- Comparing vectorized operations with Python loops

#### Library Used

- NumPy

### Task 1: Creating 2D NumPy Array

#### Step 1.1: Import NumPy

Import NumPy for array-based numerical operations.

In [1]:
import numpy as np

#### Step 1.2: Create a 2D NumPy Array

Create a 2D array for numerical analysis.

In [2]:
data = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [20, 30, 40],
    [25, 35, 45]
])

data

array([[10, 20, 30],
       [15, 25, 35],
       [20, 30, 40],
       [25, 35, 45]])

#### Step 1.3 :Compute Row Means and Column Maxima 

Calculate row means and column maxima using NumPy aggregation functions.

In [3]:
row_means = np.mean(data, axis=1)
column_maxima = np.max(data, axis=0)

row_means, column_maxima

(array([20., 25., 30., 35.]), array([25, 35, 45]))

### Task 2: Normalize Each Column

#### Step 2.1: Normalize Columns

Normalize each column to the range 0–1 using vectorized NumPy operations.

In [5]:
column_min = data.min(axis=0)
column_max = data.max(axis=0)

normalized_data = (data - column_min) / (column_max - column_min)

normalized_data

array([[0.        , 0.        , 0.        ],
       [0.33333333, 0.33333333, 0.33333333],
       [0.66666667, 0.66666667, 0.66666667],
       [1.        , 1.        , 1.        ]])

### Task 3: Applying Broadcasting

#### Step 3.1: Subtract Column Means

Use NumPy broadcasting to subtract column means from every row.

In [7]:
column_means = data.mean(axis=0)

centered_data = data - column_means

centered_data

array([[-7.5, -7.5, -7.5],
       [-2.5, -2.5, -2.5],
       [ 2.5,  2.5,  2.5],
       [ 7.5,  7.5,  7.5]])

### Task 4: Compare Vectorized Operation with Python Loop

#### Step 4.1: Compare Vectorized Operation and Loop

Compare the execution time of a NumPy vectorized operation with an equivalent Python loop.

In [8]:
import time

large_data = np.random.rand(1000000)

In [9]:
start = time.time()

vectorized_result = large_data * 2

vectorized_time = time.time() - start

print("Vectorized Time:", vectorized_time)

Vectorized Time: 0.011917829513549805


In [10]:
start = time.time()

loop_result = []

for value in large_data:
    loop_result.append(value * 2)

loop_time = time.time() - start

print("Loop Time:", loop_time)

Loop Time: 0.2640969753265381


In [11]:
print("Speed Difference:", loop_time / vectorized_time)

Speed Difference: 22.159821553603937


## Overall Observations

- NumPy provides efficient array-based operations for numerical computation.
- Vectorized operations reduce execution time compared to traditional Python loops.
- Broadcasting allows operations between arrays of different shapes without explicit looping.
- Column-wise normalization scales data into a common range (0–1), making it suitable for analysis.
- NumPy aggregation functions such as `mean()` and `max()` simplify statistical computations on arrays.